### ISSUE TITLE
Filter incorrect length data

### ISSUE THREAD

**Issue by andybeet** [NOAA-EDAB/mscatch#29]
Need to screen/clean length data.

eg. Goosefish 347cm long

**Comment by sgaichas** [comment]
Ha! Yes I was just calculating bin widths from the length data and this explains the Goosefish bins, which are calculated using max observed length: 
```
$binwidth
                    sizebin1 sizebin2 sizebin3 sizebin4 sizebin5
Atlantic cod              30       30       30       30       30
Atlantic herring           9        9        9        9        9
Atlantic mackerel         12       12       12       12       12
Goosefish                 70       70       70       70       70
Haddock                   20       20       20       20       20
Silver hake               17       17       17       17       17
Spiny dogfish             30       30       30       30       30
Winter flounder           17       17       17       17       17
Winter skate              23       23       23       23       23
Yellowtail flounder       14       14       14       14       14
```

**Comment by andybeet** [comment]
@sgaichas If you find any others please let me know

**Comment by sgaichas** [comment]
All the other max lengths in the mskeyrun datasets look good to me. They are either cod or spiny dogfish in the fishery dataset and max out at 150 which is completely reasonable. 

The goosefish length is in the fishery data in 2004 and unfortunately expands to a pretty large portion of biomass because it is so high. I was just going to drop it and move on but I'm afraid the catch biomass at length might be skewed for goosefish by that one.
